data_type:
  value: benign
dataset:
  value: NF-UNSW-NB15-v3
num_epochs:
  value: 100
learning_rate:
  value: 0.0001
weight_decay:
  value: 0.6
ae_weight_decay:
  value: 0.04
edim_out:
  value: 96
batch_size:
  value: 16384
fanout:
  value: 32768
agg_type:
  value: mean
num_layers:
  value: 1
mask_ratio:
  value: 0.15
patience:
  value: 20
ae_batch_size:
  value: 64
window_size:
  value: 512
step_percent:
  value: 1
ae_embedding_dim:
  value: 48
ae_dropout:
  value: 0
dropout:
  value: 0.6
positional_encoding:
  value: None
fraction:
  value: null
rank_method: 
  value: ppr_anom